#!/bin/sh -eu

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    deb-systemd-helper unmask remote-uci.socket >/dev/null || true

    if deb-systemd-helper --quiet was-enabled remote-uci.socket; then
        deb-systemd-helper enable remote-uci.socket >/dev/null || true
    else
        deb-systemd-helper update-state remote-uci.socket >/dev/null || true
    fi
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        deb-systemd-invoke stop remote-uci.service >/dev/null || true
        deb-systemd-invoke restart remote-uci.socket >/dev/null || true
    fi
fi
