#!/bin/sh

if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
    systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper mask 'remote-uci.socket' >/dev/null || true
    fi
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/remote-uci.secret
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge 'remote-uci.socket' >/dev/null || true
        deb-systemd-helper unmask 'remote-uci.socket' >/dev/null || true
    fi
fi
